unattended_spec works

diff --git a/bin/start_dynamodblocal b/bin/start_dynamodblocal
--- a/bin/start_dynamodblocal
+++ b/bin/start_dynamodblocal
@@ -1,36 +1,45 @@
 #!/bin/sh
 
+LISTEN_PORT=8000
+
 source $(dirname $0)/_dynamodblocal
 
 if [ -z $JAVA_HOME ]; then
-  echo 'ERROR: DynamoDBLocal requires JAVA_HOME to be set.'
+  echo >&2 'ERROR: DynamoDBLocal requires JAVA_HOME to be set.'
   exit 1
 fi
 
 if [ ! -x $JAVA_HOME/bin/java ]; then
-  echo 'ERROR: JAVA_HOME is set, but I do not see the java executable there.'
+  echo >&2 'ERROR: JAVA_HOME is set, but I do not see the java executable there.'
   exit 2
 fi
 
 cd $DIST_DIR
 
 if [ ! -f DynamoDBLocal.jar ] || [ ! -d DynamoDBLocal_lib ]; then
-  echo 'ERROR: Could not find DynamoDBLocal files in $DIST_DIR.'
+  echo >&2 'ERROR: Could not find DynamoDBLocal files in $DIST_DIR.'
 fi
 
-$JAVA_HOME/bin/java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -inMemory -delayTransientStatuses -port 8000 &
+hash lsof 2>/dev/null && lsof -i :$LISTEN_PORT && { echo >&2 "Something is already listening on port $LISTEN_PORT; I will not attempt to start DynamoDBLocal."; exit 1; }
+
+nohup $JAVA_HOME/bin/java -Djava.library.path=./DynamoDBLocal_lib -jar DynamoDBLocal.jar -inMemory -delayTransientStatuses -port $LISTEN_PORT 0<&- >/dev/null 2>&1 &
 pid=$!
-echo 'Launched.'
+echo "Launched to listen on port $LISTEN_PORT."
 
 echo 'Verifying that DynamoDBLocal actually started...'
-# Allow some seconds for the JDK to start and die.
-sleep 5
-kill -0 $pid
 
-if [ $? -eq 0 ]; then
-  echo "Started DynamoDBLocal at pid $pid"
-  echo $pid > $PIDFILE
-else
-  echo 'ERROR: DynamoDBLocal did not start. Sorry.'
-  exit 1
-fi
+# Allow some seconds for the JDK to start and die.
+counter=0
+while [ $counter -le 5 ]; do
+  kill -0 $pid
+  if [ $? -ne 0 ]; then
+    echo >&2 'ERROR: DynamoDBLocal died after we tried to start it!'
+    exit 1
+  else
+    counter=$(($counter + 1))
+    sleep 1
+  fi
+done
+
+echo "Started DynamoDBLocal at pid $pid to listen on port $LISTEN_PORT."
+echo $pid > $PIDFILE
diff --git a/bin/stop_dynamodblocal b/bin/stop_dynamodblocal
--- a/bin/stop_dynamodblocal
+++ b/bin/stop_dynamodblocal
@@ -14,16 +14,20 @@ pid=$(<$PIDFILE)
 echo "Killing DynamoDBLocal at pid $pid..."
 kill $pid
 
-# Let it die gracefully
-sleep 5
+counter=0
+while [ $counter -le 5 ]; do
+  kill -0 $pid 2>/dev/null
+  if [ $? -ne 0 ]; then
+    echo 'Successfully shut down DynamoDBLocal.'
+    rm -f $PIDFILE
+    exit 0
+  else
+    echo 'Still waiting for DynamoDBLocal to shut down...'
+    counter=$(($counter + 1))
+    sleep 1
+  fi
+done
 
-kill -0 $pid
-if [ $? -ne 0 ]; then
-  echo 'Successfully shut down DynamoDBLocal.'
-  rm -f $PIDFILE
-else
-  echo 'Unable to shut down DynamoDBLocal; you may need to kill it yourself.'
-  rm -f $PIDFILE
-  exit 1
-fi
-
+echo 'Unable to shut down DynamoDBLocal; you may need to kill it yourself.'
+rm -f $PIDFILE
+exit 1
